In [1]:
import torch

In [2]:
shape = (2,3)

In [3]:
ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.randn(shape)

In [4]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
random

tensor([[ 0.0247, -0.3440,  0.3985],
        [ 1.4083,  0.8962, -0.2484]])

In [7]:
mimic = torch.randn_like(ones, dtype=torch.float)

In [8]:
mimic

tensor([[ 0.6224,  0.5987,  0.8272],
        [-1.4385,  0.5438,  0.0840]])

In [9]:
a = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)
x = torch.tensor(4., requires_grad=True)

In [10]:
y= a+b

In [11]:
z= x*y

In [12]:
print(z)

tensor(20., grad_fn=<MulBackward0>)


In [13]:
print(z.grad_fn)

In [14]:
t1 = torch.tensor([[1., 2.],[4.,9.]])
t2 = torch.tensor([[3., 4.],[5., 10.]])


In [15]:
t1*t2

tensor([[ 3.,  8.],
        [20., 90.]])

In [17]:
t1@t2

tensor([[ 13.,  24.],
        [ 57., 106.]])

In [19]:
t1.mean(dim=1)

tensor([1.5000, 6.5000])

In [ ]:
torch.argmax(t1, dim=0)

tensor([1, 1])

: 