In [1]:
import torch

In [2]:
N = 10

D_in = 1

D_out = 1

X = torch.randn(N, D_in)

true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.)

true_y = X @ true_W  + true_b + torch.randn(N, D_out) * 0.1

In [3]:
X

tensor([[ 0.4345],
        [-0.4019],
        [-0.2515],
        [ 0.5255],
        [-0.0134],
        [-0.8764],
        [-0.6840],
        [ 1.0334],
        [-0.5611],
        [ 0.1712]])

In [4]:
W = torch.randn_like(true_W, requires_grad=True)
b = torch.randn_like(true_b, requires_grad=True)

In [5]:
print("Initial W: ", W)

Initial W:  tensor([[0.1365]], requires_grad=True)


In [6]:
print("Initial b: ", b)

Initial b:  tensor(1.8842, requires_grad=True)


In [7]:
y_hat = X @ W + b

In [8]:
y_hat

tensor([[1.9436],
        [1.8294],
        [1.8499],
        [1.9560],
        [1.8824],
        [1.7646],
        [1.7909],
        [2.0253],
        [1.8076],
        [1.9076]], grad_fn=<AddBackward0>)

In [9]:
true_y

tensor([[ 1.9377],
        [ 0.3732],
        [ 0.4141],
        [ 1.8163],
        [ 0.8471],
        [-0.7815],
        [-0.1896],
        [ 3.0524],
        [-0.2045],
        [ 1.5100]])

In [10]:
# hyperparams

learning_rate, epochs = 0.01, 20000

In [11]:
# re-init
W, b = torch.randn_like(true_W, requires_grad=True), torch.randn_like(true_b, requires_grad=True)

In [12]:
# for epoch in range(epochs):
#   y_hat = X @ W + b
#   loss = torch.mean((y_hat-true_y)**2)
  
#   loss.backward()
  
#   with torch.no_grad():
#     W -= learning_rate * W.grad
#     b -= learning_rate * b.grad
    
#   W.grad.zero_()
#   b.grad.zero_()
  
#   if epoch % 1000 == 0:
#     print(f"Epoch {epoch:02d}, Loss: {loss.item():.4f} W: {W.item():.3f}, b: {b.item():.3f}")
    
# print(f"final parameters: Loss: {loss.item():.4f} W: {W.item():.3f}, b: {b.item():.3f}")
# print("True parameters: W = {true_W:.3f}, b = {true_b:.3f}")

In [13]:
linear_layer = torch.nn.Linear(D_in, D_out)

y_hat_nn = linear_layer(X)

In [ ]:
y_hat_nn


tensor([[-0.0665],
        [-0.7342],
        [-0.6141],
        [ 0.0062],
        [-0.4240],
        [-1.1129],
        [-0.9593],
        [ 0.4115],
        [-0.8612],
        [-0.2767]], grad_fn=<AddmmBackward0>)

: 